- name: make blackhole drop dir
  file:
    name=/etc/bird/blackholes
    state=directory
    owner=root

- name: make filter drop dir
  file:
    name=/etc/bird/filters
    state=directory
    owner=root

- template:
    src: bird.j2
    dest: /etc/bird/bird.conf
    owner: root
  vars:
    afi: 4
  notify: reload bird

- template:
    src: bird.j2
    dest: /etc/bird/bird6.conf
    owner: root
  vars:
    afi: 6
  notify: reload bird6
