- name: update-filters.sh
  copy:
    src=update-filters.sh.j2
    dest=/root/update-filters.sh
    owner=root
    mode=0755

- cron:
    name=update_filters
    hour=03
    minute="{{ 59 |random(seed=inventory_hostname) }}"
    state=present
    job="chronic /root/update-filters.sh"

- command: "{{ item }}"
  with_items:
    - "/root/update-filters.sh"
